<?php

use Illuminate\Database\Seeder;
use App\Model\States;

class StatesTableSeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
//
	DB::table('states')->delete();
	$states = array(
		array('name' => "Andaman and Nicobar Islands",'country_id' => 101),
		array('name' => "Andhra Pradesh",'country_id' => 101),
		array('name' => "Arunachal Pradesh",'country_id' => 101),
		array('name' => "Assam",'country_id' => 101),
		array('name' => "Bihar",'country_id' => 101),
		array('name' => "Chandigarh",'country_id' => 101),
		array('name' => "Chhattisgarh",'country_id' => 101),
		array('name' => "Dadra and Nagar Haveli",'country_id' => 101),
		array('name' => "Daman and Diu",'country_id' => 101),
		array('name' => "Delhi",'country_id' => 101),
		array('name' => "Goa",'country_id' => 101),
		array('name' => "Gujarat",'country_id' => 101),
		array('name' => "Haryana",'country_id' => 101),
		array('name' => "Himachal Pradesh",'country_id' => 101),
		array('name' => "Jammu and Kashmir",'country_id' => 101),
		array('name' => "Jharkhand",'country_id' => 101),
		array('name' => "Karnataka",'country_id' => 101),
		array('name' => "Kenmore",'country_id' => 101),
		array('name' => "Kerala",'country_id' => 101),
		array('name' => "Lakshadweep",'country_id' => 101),
		array('name' => "Madhya Pradesh",'country_id' => 101),
		array('name' => "Maharashtra",'country_id' => 101),
		array('name' => "Manipur",'country_id' => 101),
		array('name' => "Meghalaya",'country_id' => 101),
		array('name' => "Mizoram",'country_id' => 101),
		array('name' => "Nagaland",'country_id' => 101),
		array('name' => "Narora",'country_id' => 101),
		array('name' => "Natwar",'country_id' => 101),
		array('name' => "Odisha",'country_id' => 101),
		array('name' => "Paschim Medinipur",'country_id' => 101),
		array('name' => "Pondicherry",'country_id' => 101),
		array('name' => "Punjab",'country_id' => 101),
		array('name' => "Rajasthan",'country_id' => 101),
		array('name' => "Sikkim",'country_id' => 101),
		array('name' => "Tamil Nadu",'country_id' => 101),
		array('name' => "Telangana",'country_id' => 101),
		array('name' => "Tripura",'country_id' => 101),
		array('name' => "Uttar Pradesh",'country_id' => 101),
		array('name' => "Uttarakhand",'country_id' => 101),
		array('name' => "Vaishali",'country_id' => 101),
		array('name' => "West Bengal",'country_id' => 101),
		array('name' => "Auckland",'country_id' => 13),
		array('name' => "Australian Capital Territory",'country_id' => 13),
		array('name' => "Balgowlah",'country_id' => 13),
		array('name' => "Balmain",'country_id' => 13),
		array('name' => "Bankstown",'country_id' => 13),
		array('name' => "Baulkham Hills",'country_id' => 13),
		array('name' => "Bonnet Bay",'country_id' => 13),
		array('name' => "Camberwell",'country_id' => 13),
		array('name' => "Carole Park",'country_id' => 13),
		array('name' => "Castle Hill",'country_id' => 13),
		array('name' => "Caulfield",'country_id' => 13),
		array('name' => "Chatswood",'country_id' => 13),
		array('name' => "Cheltenham",'country_id' => 13),
		array('name' => "Cherrybrook",'country_id' => 13),
		array('name' => "Clayton",'country_id' => 13),
		array('name' => "Collingwood",'country_id' => 13),
		array('name' => "Frenchs Forest",'country_id' => 13),
		array('name' => "Hawthorn",'country_id' => 13),
		array('name' => "Jannnali",'country_id' => 13),
		array('name' => "Knoxfield",'country_id' => 13),
		array('name' => "Melbourne",'country_id' => 13),
		array('name' => "New South Wales",'country_id' => 13),
		array('name' => "Northern Territory",'country_id' => 13),
		array('name' => "Perth",'country_id' => 13),
		array('name' => "Queensland",'country_id' => 13),
		array('name' => "South Australia",'country_id' => 13),
		array('name' => "Tasmania",'country_id' => 13),
		array('name' => "Templestowe",'country_id' => 13),
		array('name' => "Victoria",'country_id' => 13),
		array('name' => "Werribee south",'country_id' => 13),
		array('name' => "Western Australia",'country_id' => 13),
		array('name' => "Wheeler",'country_id' => 13),
		array('name' => "Bagar Hat",'country_id' => 18),
		array('name' => "Bandarban",'country_id' => 18),
		array('name' => "Barguna",'country_id' => 18),
		array('name' => "Barisal",'country_id' => 18),
		array('name' => "Bhola",'country_id' => 18),
		array('name' => "Bogora",'country_id' => 18),
		array('name' => "Brahman Bariya",'country_id' => 18),
		array('name' => "Chandpur",'country_id' => 18),
		array('name' => "Chattagam",'country_id' => 18),
		array('name' => "Chittagong Division",'country_id' => 18),
		array('name' => "Chuadanga",'country_id' => 18),
		array('name' => "Dhaka",'country_id' => 18),
		array('name' => "Dinajpur",'country_id' => 18),
		array('name' => "Faridpur",'country_id' => 18),
		array('name' => "Feni",'country_id' => 18),
		array('name' => "Gaybanda",'country_id' => 18),
		array('name' => "Gazipur",'country_id' => 18),
		array('name' => "Gopalganj",'country_id' => 18),
		array('name' => "Habiganj",'country_id' => 18),
		array('name' => "Jaipur Hat",'country_id' => 18),
		array('name' => "Jamalpur",'country_id' => 18),
		array('name' => "Jessor",'country_id' => 18),
		array('name' => "Jhalakati",'country_id' => 18),
		array('name' => "Jhanaydah",'country_id' => 18),
		array('name' => "Khagrachhari",'country_id' => 18),
		array('name' => "Khulna",'country_id' => 18),
		array('name' => "Kishorganj",'country_id' => 18),
		array('name' => "Koks Bazar",'country_id' => 18),
		array('name' => "Komilla",'country_id' => 18),
		array('name' => "Kurigram",'country_id' => 18),
		array('name' => "Kushtiya",'country_id' => 18),
		array('name' => "Lakshmipur",'country_id' => 18),
		array('name' => "Lalmanir Hat",'country_id' => 18),
		array('name' => "Madaripur",'country_id' => 18),
		array('name' => "Magura",'country_id' => 18),
		array('name' => "Maimansingh",'country_id' => 18),
		array('name' => "Manikganj",'country_id' => 18),
		array('name' => "Maulvi Bazar",'country_id' => 18),
		array('name' => "Meherpur",'country_id' => 18),
		array('name' => "Munshiganj",'country_id' => 18),
		array('name' => "Naral",'country_id' => 18),
		array('name' => "Narayanganj",'country_id' => 18),
		array('name' => "Narsingdi",'country_id' => 18),
		array('name' => "Nator",'country_id' => 18),
		array('name' => "Naugaon",'country_id' => 18),
		array('name' => "Nawabganj",'country_id' => 18),
		array('name' => "Netrakona",'country_id' => 18),
		array('name' => "Nilphamari",'country_id' => 18),
		array('name' => "Noakhali",'country_id' => 18),
		array('name' => "Pabna",'country_id' => 18),
		array('name' => "Panchagarh",'country_id' => 18),
		array('name' => "Patuakhali",'country_id' => 18),
		array('name' => "Pirojpur",'country_id' => 18),
		array('name' => "Rajbari",'country_id' => 18),
		array('name' => "Rajshahi",'country_id' => 18),
		array('name' => "Rangamati",'country_id' => 18),
		array('name' => "Rangpur",'country_id' => 18),
		array('name' => "Satkhira",'country_id' => 18),
		array('name' => "Shariatpur",'country_id' => 18),
		array('name' => "Sherpur",'country_id' => 18),
		array('name' => "Silhat",'country_id' => 18),
		array('name' => "Sirajganj",'country_id' => 18),
		array('name' => "Sunamganj",'country_id' => 18),
		array('name' => "Tangayal",'country_id' => 18),
		array('name' => "Thakurgaon",'country_id' => 18),
		array('name' => "Alberta",'country_id' => 38),
		array('name' => "British Columbia",'country_id' => 38),
		array('name' => "Manitoba",'country_id' => 38),
		array('name' => "New Brunswick",'country_id' => 38),
		array('name' => "Newfoundland and Labrador",'country_id' => 38),
		array('name' => "Northwest Territories",'country_id' => 38),
		array('name' => "Nova Scotia",'country_id' => 38),
		array('name' => "Nunavut",'country_id' => 38),
		array('name' => "Ontario",'country_id' => 38),
		array('name' => "Prince Edward Island",'country_id' => 38),
		array('name' => "Quebec",'country_id' => 38),
		array('name' => "Saskatchewan",'country_id' => 38),
		array('name' => "Yukon",'country_id' => 38),
		array('name' => "Ain",'country_id' => 75),
		array('name' => "Aisne",'country_id' => 75),
		array('name' => "Albi Le Sequestre",'country_id' => 75),
		array('name' => "Allier",'country_id' => 75),
		array('name' => "Alpes-Cote dAzur",'country_id' => 75),
		array('name' => "Alpes-Maritimes",'country_id' => 75),
		array('name' => "Alpes-de-Haute-Provence",'country_id' => 75),
		array('name' => "Alsace",'country_id' => 75),
		array('name' => "Aquitaine",'country_id' => 75),
		array('name' => "Ardeche",'country_id' => 75),
		array('name' => "Ardennes",'country_id' => 75),
		array('name' => "Ariege",'country_id' => 75),
		array('name' => "Aube",'country_id' => 75),
		array('name' => "Aude",'country_id' => 75),
		array('name' => "Auvergne",'country_id' => 75),
		array('name' => "Aveyron",'country_id' => 75),
		array('name' => "Bas-Rhin",'country_id' => 75),
		array('name' => "Basse-Normandie",'country_id' => 75),
		array('name' => "Bouches-du-Rhone",'country_id' => 75),
		array('name' => "Bourgogne",'country_id' => 75),
		array('name' => "Bretagne",'country_id' => 75),
		array('name' => "Brittany",'country_id' => 75),
		array('name' => "Burgundy",'country_id' => 75),
		array('name' => "Calvados",'country_id' => 75),
		array('name' => "Cantal",'country_id' => 75),
		array('name' => "Cedex",'country_id' => 75),
		array('name' => "Centre",'country_id' => 75),
		array('name' => "Charente",'country_id' => 75),
		array('name' => "Charente-Maritime",'country_id' => 75),
		array('name' => "Cher",'country_id' => 75),
		array('name' => "Correze",'country_id' => 75),
		array('name' => "Corse-du-Sud",'country_id' => 75),
		array('name' => "Cote-d'Or",'country_id' => 75),
		array('name' => "Cotes-d'Armor",'country_id' => 75),
		array('name' => "Creuse",'country_id' => 75),
		array('name' => "Crolles",'country_id' => 75),
		array('name' => "Deux-Sevres",'country_id' => 75),
		array('name' => "Dordogne",'country_id' => 75),
		array('name' => "Doubs",'country_id' => 75),
		array('name' => "Drome",'country_id' => 75),
		array('name' => "Essonne",'country_id' => 75),
		array('name' => "Eure",'country_id' => 75),
		array('name' => "Eure-et-Loir",'country_id' => 75),
		array('name' => "Feucherolles",'country_id' => 75),
		array('name' => "Finistere",'country_id' => 75),
		array('name' => "Franche-Comte",'country_id' => 75),
		array('name' => "Gard",'country_id' => 75),
		array('name' => "Gers",'country_id' => 75),
		array('name' => "Gironde",'country_id' => 75),
		array('name' => "Haut-Rhin",'country_id' => 75),
		array('name' => "Haute-Corse",'country_id' => 75),
		array('name' => "Haute-Garonne",'country_id' => 75),
		array('name' => "Haute-Loire",'country_id' => 75),
		array('name' => "Haute-Marne",'country_id' => 75),
		array('name' => "Haute-Saone",'country_id' => 75),
		array('name' => "Haute-Savoie",'country_id' => 75),
		array('name' => "Haute-Vienne",'country_id' => 75),
		array('name' => "Hautes-Alpes",'country_id' => 75),
		array('name' => "Hautes-Pyrenees",'country_id' => 75),
		array('name' => "Hauts-de-Seine",'country_id' => 75),
		array('name' => "Herault",'country_id' => 75),
		array('name' => "Ile-de-France",'country_id' => 75),
		array('name' => "Ille-et-Vilaine",'country_id' => 75),
		array('name' => "Indre",'country_id' => 75),
		array('name' => "Indre-et-Loire",'country_id' => 75),
		array('name' => "Isere",'country_id' => 75),
		array('name' => "Jura",'country_id' => 75),
		array('name' => "Klagenfurt",'country_id' => 75),
		array('name' => "Landes",'country_id' => 75),
		array('name' => "Languedoc-Roussillon",'country_id' => 75),
		array('name' => "Larcay",'country_id' => 75),
		array('name' => "Le Castellet",'country_id' => 75),
		array('name' => "Le Creusot",'country_id' => 75),
		array('name' => "Limousin",'country_id' => 75),
		array('name' => "Loir-et-Cher",'country_id' => 75),
		array('name' => "Loire",'country_id' => 75),
		array('name' => "Loire-Atlantique",'country_id' => 75),
		array('name' => "Loiret",'country_id' => 75),
		array('name' => "Lorraine",'country_id' => 75),
		array('name' => "Lot",'country_id' => 75),
		array('name' => "Lot-et-Garonne",'country_id' => 75),
		array('name' => "Lower Normandy",'country_id' => 75),
		array('name' => "Lozere",'country_id' => 75),
		array('name' => "Maine-et-Loire",'country_id' => 75),
		array('name' => "Manche",'country_id' => 75),
		array('name' => "Marne",'country_id' => 75),
		array('name' => "Mayenne",'country_id' => 75),
		array('name' => "Meurthe-et-Moselle",'country_id' => 75),
		array('name' => "Meuse",'country_id' => 75),
		array('name' => "Midi-Pyrenees",'country_id' => 75),
		array('name' => "Morbihan",'country_id' => 75),
		array('name' => "Moselle",'country_id' => 75),
		array('name' => "Nievre",'country_id' => 75),
		array('name' => "Nord",'country_id' => 75),
		array('name' => "Nord-Pas-de-Calais",'country_id' => 75),
		array('name' => "Oise",'country_id' => 75),
		array('name' => "Orne",'country_id' => 75),
		array('name' => "Paris",'country_id' => 75),
		array('name' => "Pas-de-Calais",'country_id' => 75),
		array('name' => "Pays de la Loire",'country_id' => 75),
		array('name' => "Pays-de-la-Loire",'country_id' => 75),
		array('name' => "Picardy",'country_id' => 75),
		array('name' => "Puy-de-Dome",'country_id' => 75),
		array('name' => "Pyrenees-Atlantiques",'country_id' => 75),
		array('name' => "Pyrenees-Orientales",'country_id' => 75),
		array('name' => "Quelmes",'country_id' => 75),
		array('name' => "Rhone",'country_id' => 75),
		array('name' => "Rhone-Alpes",'country_id' => 75),
		array('name' => "Saint Ouen",'country_id' => 75),
		array('name' => "Saint Viatre",'country_id' => 75),
		array('name' => "Saone-et-Loire",'country_id' => 75),
		array('name' => "Sarthe",'country_id' => 75),
		array('name' => "Savoie",'country_id' => 75),
		array('name' => "Seine-Maritime",'country_id' => 75),
		array('name' => "Seine-Saint-Denis",'country_id' => 75),
		array('name' => "Seine-et-Marne",'country_id' => 75),
		array('name' => "Somme",'country_id' => 75),
		array('name' => "Sophia Antipolis",'country_id' => 75),
		array('name' => "Souvans",'country_id' => 75),
		array('name' => "Tarn",'country_id' => 75),
		array('name' => "Tarn-et-Garonne",'country_id' => 75),
		array('name' => "Territoire de Belfort",'country_id' => 75),
		array('name' => "Treignac",'country_id' => 75),
		array('name' => "Upper Normandy",'country_id' => 75),
		array('name' => "Val-d'Oise",'country_id' => 75),
		array('name' => "Val-de-Marne",'country_id' => 75),
		array('name' => "Var",'country_id' => 75),
		array('name' => "Vaucluse",'country_id' => 75),
		array('name' => "Vellise",'country_id' => 75),
		array('name' => "Vendee",'country_id' => 75),
		array('name' => "Vienne",'country_id' => 75),
		array('name' => "Vosges",'country_id' => 75),
		array('name' => "Yonne",'country_id' => 75),
		array('name' => "Yvelines",'country_id' => 75),
		array('name' => "Auvergne",'country_id' => 82),
		array('name' => "Baden-Wurttemberg",'country_id' => 82),
		array('name' => "Bavaria",'country_id' => 82),
		array('name' => "Bayern",'country_id' => 82),
		array('name' => "Beilstein Wurtt",'country_id' => 82),
		array('name' => "Berlin",'country_id' => 82),
		array('name' => "Brandenburg",'country_id' => 82),
		array('name' => "Bremen",'country_id' => 82),
		array('name' => "Dreisbach",'country_id' => 82),
		array('name' => "Freistaat Bayern",'country_id' => 82),
		array('name' => "Hamburg",'country_id' => 82),
		array('name' => "Hannover",'country_id' => 82),
		array('name' => "Heroldstatt",'country_id' => 82),
		array('name' => "Hessen",'country_id' => 82),
		array('name' => "Kortenberg",'country_id' => 82),
		array('name' => "Laasdorf",'country_id' => 82),
		array('name' => "Land Baden-Wurttemberg",'country_id' => 82),
		array('name' => "Land Bayern",'country_id' => 82),
		array('name' => "Land Brandenburg",'country_id' => 82),
		array('name' => "Land Hessen",'country_id' => 82),
		array('name' => "Land Mecklenburg-Vorpommern",'country_id' => 82),
		array('name' => "Land Nordrhein-Westfalen",'country_id' => 82),
		array('name' => "Land Rheinland-Pfalz",'country_id' => 82),
		array('name' => "Land Sachsen",'country_id' => 82),
		array('name' => "Land Sachsen-Anhalt",'country_id' => 82),
		array('name' => "Land Thuringen",'country_id' => 82),
		array('name' => "Lower Saxony",'country_id' => 82),
		array('name' => "Mecklenburg-Vorpommern",'country_id' => 82),
		array('name' => "Mulfingen",'country_id' => 82),
		array('name' => "Munich",'country_id' => 82),
		array('name' => "Neubeuern",'country_id' => 82),
		array('name' => "Niedersachsen",'country_id' => 82),
		array('name' => "Noord-Holland",'country_id' => 82),
		array('name' => "Nordrhein-Westfalen",'country_id' => 82),
		array('name' => "North Rhine-Westphalia",'country_id' => 82),
		array('name' => "Osterode",'country_id' => 82),
		array('name' => "Rheinland-Pfalz",'country_id' => 82),
		array('name' => "Rhineland-Palatinate",'country_id' => 82),
		array('name' => "Saarland",'country_id' => 82),
		array('name' => "Sachsen",'country_id' => 82),
		array('name' => "Sachsen-Anhalt",'country_id' => 82),
		array('name' => "Saxony",'country_id' => 82),
		array('name' => "Schleswig-Holstein",'country_id' => 82),
		array('name' => "Thuringia",'country_id' => 82),
		array('name' => "Webling",'country_id' => 82),
		array('name' => "Weinstrabe",'country_id' => 82),
		array('name' => "schlobborn",'country_id' => 82),
		array('name' => "Abruzzi",'country_id' => 107),
		array('name' => "Abruzzo",'country_id' => 107),
		array('name' => "Agrigento",'country_id' => 107),
		array('name' => "Alessandria",'country_id' => 107),
		array('name' => "Ancona",'country_id' => 107),
		array('name' => "Arezzo",'country_id' => 107),
		array('name' => "Ascoli Piceno",'country_id' => 107),
		array('name' => "Asti",'country_id' => 107),
		array('name' => "Avellino",'country_id' => 107),
		array('name' => "Bari",'country_id' => 107),
		array('name' => "Basilicata",'country_id' => 107),
		array('name' => "Belluno",'country_id' => 107),
		array('name' => "Benevento",'country_id' => 107),
		array('name' => "Bergamo",'country_id' => 107),
		array('name' => "Biella",'country_id' => 107),
		array('name' => "Bologna",'country_id' => 107),
		array('name' => "Bolzano",'country_id' => 107),
		array('name' => "Brescia",'country_id' => 107),
		array('name' => "Brindisi",'country_id' => 107),
		array('name' => "Calabria",'country_id' => 107),
		array('name' => "Campania",'country_id' => 107),
		array('name' => "Cartoceto",'country_id' => 107),
		array('name' => "Caserta",'country_id' => 107),
		array('name' => "Catania",'country_id' => 107),
		array('name' => "Chieti",'country_id' => 107),
		array('name' => "Como",'country_id' => 107),
		array('name' => "Cosenza",'country_id' => 107),
		array('name' => "Cremona",'country_id' => 107),
		array('name' => "Cuneo",'country_id' => 107),
		array('name' => "Emilia-Romagna",'country_id' => 107),
		array('name' => "Ferrara",'country_id' => 107),
		array('name' => "Firenze",'country_id' => 107),
		array('name' => "Florence",'country_id' => 107),
		array('name' => "Forli-Cesena ",'country_id' => 107),
		array('name' => "Friuli-Venezia Giulia",'country_id' => 107),
		array('name' => "Frosinone",'country_id' => 107),
		array('name' => "Genoa",'country_id' => 107),
		array('name' => "Gorizia",'country_id' => 107),
		array('name' => "L'Aquila",'country_id' => 107),
		array('name' => "Lazio",'country_id' => 107),
		array('name' => "Lecce",'country_id' => 107),
		array('name' => "Lecco",'country_id' => 107),
		array('name' => "Lecco Province",'country_id' => 107),
		array('name' => "Liguria",'country_id' => 107),
		array('name' => "Lodi",'country_id' => 107),
		array('name' => "Lombardia",'country_id' => 107),
		array('name' => "Lombardy",'country_id' => 107),
		array('name' => "Macerata",'country_id' => 107),
		array('name' => "Mantova",'country_id' => 107),
		array('name' => "Marche",'country_id' => 107),
		array('name' => "Messina",'country_id' => 107),
		array('name' => "Milan",'country_id' => 107),
		array('name' => "Modena",'country_id' => 107),
		array('name' => "Molise",'country_id' => 107),
		array('name' => "Molteno",'country_id' => 107),
		array('name' => "Montenegro",'country_id' => 107),
		array('name' => "Monza and Brianza",'country_id' => 107),
		array('name' => "Naples",'country_id' => 107),
		array('name' => "Novara",'country_id' => 107),
		array('name' => "Padova",'country_id' => 107),
		array('name' => "Parma",'country_id' => 107),
		array('name' => "Pavia",'country_id' => 107),
		array('name' => "Perugia",'country_id' => 107),
		array('name' => "Pesaro-Urbino",'country_id' => 107),
		array('name' => "Piacenza",'country_id' => 107),
		array('name' => "Piedmont",'country_id' => 107),
		array('name' => "Piemonte",'country_id' => 107),
		array('name' => "Pisa",'country_id' => 107),
		array('name' => "Pordenone",'country_id' => 107),
		array('name' => "Potenza",'country_id' => 107),
		array('name' => "Puglia",'country_id' => 107),
		array('name' => "Reggio Emilia",'country_id' => 107),
		array('name' => "Rimini",'country_id' => 107),
		array('name' => "Roma",'country_id' => 107),
		array('name' => "Salerno",'country_id' => 107),
		array('name' => "Sardegna",'country_id' => 107),
		array('name' => "Sassari",'country_id' => 107),
		array('name' => "Savona",'country_id' => 107),
		array('name' => "Sicilia",'country_id' => 107),
		array('name' => "Siena",'country_id' => 107),
		array('name' => "Sondrio",'country_id' => 107),
		array('name' => "South Tyrol",'country_id' => 107),
		array('name' => "Taranto",'country_id' => 107),
		array('name' => "Teramo",'country_id' => 107),
		array('name' => "Torino",'country_id' => 107),
		array('name' => "Toscana",'country_id' => 107),
		array('name' => "Trapani",'country_id' => 107),
		array('name' => "Trentino-Alto Adige",'country_id' => 107),
		array('name' => "Trento",'country_id' => 107),
		array('name' => "Treviso",'country_id' => 107),
		array('name' => "Udine",'country_id' => 107),
		array('name' => "Umbria",'country_id' => 107),
		array('name' => "Valle d'Aosta",'country_id' => 107),
		array('name' => "Varese",'country_id' => 107),
		array('name' => "Veneto",'country_id' => 107),
		array('name' => "Venezia",'country_id' => 107),
		array('name' => "Verbano-Cusio-Ossola",'country_id' => 107),
		array('name' => "Vercelli",'country_id' => 107),
		array('name' => "Verona",'country_id' => 107),
		array('name' => "Vicenza",'country_id' => 107),
		array('name' => "Viterbo",'country_id' => 107),
		array('name' => "Al Asimah",'country_id' => 117),
		array('name' => "Hawalli",'country_id' => 117),
		array('name' => "Mishref",'country_id' => 117),
		array('name' => "Qadesiya",'country_id' => 117),
		array('name' => "Safat",'country_id' => 117),
		array('name' => "Salmiya",'country_id' => 117),
		array('name' => "al-Ahmadi",'country_id' => 117),
		array('name' => "al-Farwaniyah",'country_id' => 117),
		array('name' => "al-Jahra",'country_id' => 117),
		array('name' => "al-Kuwayt",'country_id' => 117),
		array('name' => "Johor",'country_id' => 132),
		array('name' => "Kedah",'country_id' => 132),
		array('name' => "Kelantan",'country_id' => 132),
		array('name' => "Kuala Lumpur",'country_id' => 132),
		array('name' => "Labuan",'country_id' => 132),
		array('name' => "Melaka",'country_id' => 132),
		array('name' => "Negeri Johor",'country_id' => 132),
		array('name' => "Negeri Sembilan",'country_id' => 132),
		array('name' => "Pahang",'country_id' => 132),
		array('name' => "Penang",'country_id' => 132),
		array('name' => "Perak",'country_id' => 132),
		array('name' => "Perlis",'country_id' => 132),
		array('name' => "Pulau Pinang",'country_id' => 132),
		array('name' => "Sabah",'country_id' => 132),
		array('name' => "Sarawak",'country_id' => 132),
		array('name' => "Selangor",'country_id' => 132),
		array('name' => "Sembilan",'country_id' => 132),
		array('name' => "Terengganu",'country_id' => 132),
		array('name' => "Bagmati",'country_id' => 153),
		array('name' => "Bheri",'country_id' => 153),
		array('name' => "Dhawalagiri",'country_id' => 153),
		array('name' => "Gandaki",'country_id' => 153),
		array('name' => "Janakpur",'country_id' => 153),
		array('name' => "Karnali",'country_id' => 153),
		array('name' => "Koshi",'country_id' => 153),
		array('name' => "Lumbini",'country_id' => 153),
		array('name' => "Mahakali",'country_id' => 153),
		array('name' => "Mechi",'country_id' => 153),
		array('name' => "Narayani",'country_id' => 153),
		array('name' => "Rapti",'country_id' => 153),
		array('name' => "Sagarmatha",'country_id' => 153),
		array('name' => "Seti",'country_id' => 153),
		array('name' => "Area Outside Region",'country_id' => 157),
		array('name' => "Auckland",'country_id' => 157),
		array('name' => "Bay of Plenty",'country_id' => 157),
		array('name' => "Canterbury",'country_id' => 157),
		array('name' => "Christchurch",'country_id' => 157),
		array('name' => "Gisborne",'country_id' => 157),
		array('name' => "Hawke's Bay",'country_id' => 157),
		array('name' => "Manawatu-Wanganui",'country_id' => 157),
		array('name' => "Marlborough",'country_id' => 157),
		array('name' => "Nelson",'country_id' => 157),
		array('name' => "Northland",'country_id' => 157),
		array('name' => "Otago",'country_id' => 157),
		array('name' => "Rodney",'country_id' => 157),
		array('name' => "Southland",'country_id' => 157),
		array('name' => "Taranaki",'country_id' => 157),
		array('name' => "Tasman",'country_id' => 157),
		array('name' => "Waikato",'country_id' => 157),
		array('name' => "Wellington",'country_id' => 157),
		array('name' => "West Coast",'country_id' => 157),
		array('name' => "Azad kashmir",'country_id' => 166),
		array('name' => "Balochistan",'country_id' => 166),
		array('name' => "Fata",'country_id' => 166),
		array('name' => "Gilgit–baltistan",'country_id' => 166),
		array('name' => "Islamabad capital territory",'country_id' => 166),
		array('name' => "Khyber Pakhtunkhwa",'country_id' => 166),
		array('name' => "Punjab",'country_id' => 166),
		array('name' => "Sindh",'country_id' => 166),
		array('name' => "Doha",'country_id' => 178),
		array('name' => "Jarian-al-Batnah",'country_id' => 178),
		array('name' => "Umm Salal",'country_id' => 178),
		array('name' => "ad-Dawhah",'country_id' => 178),
		array('name' => "al-Ghuwayriyah",'country_id' => 178),
		array('name' => "al-Jumayliyah",'country_id' => 178),
		array('name' => "al-Khawr",'country_id' => 178),
		array('name' => "al-Wakrah",'country_id' => 178),
		array('name' => "ar-Rayyan",'country_id' => 178),
		array('name' => "ash-Shamal",'country_id' => 178),
		array('name' => "Al Khobar",'country_id' => 191),
		array('name' => "Aseer",'country_id' => 191),
		array('name' => "Ash Sharqiyah",'country_id' => 191),
		array('name' => "Asir",'country_id' => 191),
		array('name' => "Central Province",'country_id' => 191),
		array('name' => "Eastern Province",'country_id' => 191),
		array('name' => "Ha'il",'country_id' => 191),
		array('name' => "Jawf",'country_id' => 191),
		array('name' => "Jizan",'country_id' => 191),
		array('name' => "Makkah",'country_id' => 191),
		array('name' => "Najran",'country_id' => 191),
		array('name' => "Qasim",'country_id' => 191),
		array('name' => "Tabuk",'country_id' => 191),
		array('name' => "Western Province",'country_id' => 191),
		array('name' => "al-Bahah",'country_id' => 191),
		array('name' => "al-Hudud-ash-Shamaliyah",'country_id' => 191),
		array('name' => "al-Madinah",'country_id' => 191),
		array('name' => "ar-Riyad",'country_id' => 191),
		array('name' => "Singapore",'country_id' => 196),
		array('name' => "A Coruna",'country_id' => 205),
		array('name' => "Alacant",'country_id' => 205),
		array('name' => "Alava",'country_id' => 205),
		array('name' => "Albacete",'country_id' => 205),
		array('name' => "Almeria",'country_id' => 205),
		array('name' => "Andalucia",'country_id' => 205),
		array('name' => "Asturias",'country_id' => 205),
		array('name' => "Avila",'country_id' => 205),
		array('name' => "Badajoz",'country_id' => 205),
		array('name' => "Balears",'country_id' => 205),
		array('name' => "Barcelona",'country_id' => 205),
		array('name' => "Bertamirans",'country_id' => 205),
		array('name' => "Biscay",'country_id' => 205),
		array('name' => "Burgos",'country_id' => 205),
		array('name' => "Caceres",'country_id' => 205),
		array('name' => "Cadiz",'country_id' => 205),
		array('name' => "Cantabria",'country_id' => 205),
		array('name' => "Castello",'country_id' => 205),
		array('name' => "Catalunya",'country_id' => 205),
		array('name' => "Ceuta",'country_id' => 205),
		array('name' => "Ciudad Real",'country_id' => 205),
		array('name' => "Comunidad Autonoma de Canarias",'country_id' => 205),
		array('name' => "Comunidad Autonoma de Cataluna",'country_id' => 205),
		array('name' => "Comunidad Autonoma de Galicia",'country_id' => 205),
		array('name' => "Comunidad Autonoma de las Isla",'country_id' => 205),
		array('name' => "Comunidad Autonoma del Princip",'country_id' => 205),
		array('name' => "Comunidad Valenciana",'country_id' => 205),
		array('name' => "Cordoba",'country_id' => 205),
		array('name' => "Cuenca",'country_id' => 205),
		array('name' => "Gipuzkoa",'country_id' => 205),
		array('name' => "Girona",'country_id' => 205),
		array('name' => "Granada",'country_id' => 205),
		array('name' => "Guadalajara",'country_id' => 205),
		array('name' => "Guipuzcoa",'country_id' => 205),
		array('name' => "Huelva",'country_id' => 205),
		array('name' => "Huesca",'country_id' => 205),
		array('name' => "Jaen",'country_id' => 205),
		array('name' => "La Rioja",'country_id' => 205),
		array('name' => "Las Palmas",'country_id' => 205),
		array('name' => "Leon",'country_id' => 205),
		array('name' => "Lerida",'country_id' => 205),
		array('name' => "Lleida",'country_id' => 205),
		array('name' => "Lugo",'country_id' => 205),
		array('name' => "Madrid",'country_id' => 205),
		array('name' => "Malaga",'country_id' => 205),
		array('name' => "Melilla",'country_id' => 205),
		array('name' => "Murcia",'country_id' => 205),
		array('name' => "Navarra",'country_id' => 205),
		array('name' => "Ourense",'country_id' => 205),
		array('name' => "Pais Vasco",'country_id' => 205),
		array('name' => "Palencia",'country_id' => 205),
		array('name' => "Pontevedra",'country_id' => 205),
		array('name' => "Salamanca",'country_id' => 205),
		array('name' => "Santa Cruz de Tenerife",'country_id' => 205),
		array('name' => "Segovia",'country_id' => 205),
		array('name' => "Sevilla",'country_id' => 205),
		array('name' => "Soria",'country_id' => 205),
		array('name' => "Tarragona",'country_id' => 205),
		array('name' => "Tenerife",'country_id' => 205),
		array('name' => "Teruel",'country_id' => 205),
		array('name' => "Toledo",'country_id' => 205),
		array('name' => "Valencia",'country_id' => 205),
		array('name' => "Valladolid",'country_id' => 205),
		array('name' => "Vizcaya",'country_id' => 205),
		array('name' => "Zamora",'country_id' => 205),
		array('name' => "Zaragoza",'country_id' => 205),
		array('name' => "Amparai",'country_id' => 206),
		array('name' => "Anuradhapuraya",'country_id' => 206),
		array('name' => "Badulla",'country_id' => 206),
		array('name' => "Boralesgamuwa",'country_id' => 206),
		array('name' => "Colombo",'country_id' => 206),
		array('name' => "Galla",'country_id' => 206),
		array('name' => "Gampaha",'country_id' => 206),
		array('name' => "Hambantota",'country_id' => 206),
		array('name' => "Kalatura",'country_id' => 206),
		array('name' => "Kegalla",'country_id' => 206),
		array('name' => "Kilinochchi",'country_id' => 206),
		array('name' => "Kurunegala",'country_id' => 206),
		array('name' => "Madakalpuwa",'country_id' => 206),
		array('name' => "Maha Nuwara",'country_id' => 206),
		array('name' => "Malwana",'country_id' => 206),
		array('name' => "Mannarama",'country_id' => 206),
		array('name' => "Matale",'country_id' => 206),
		array('name' => "Matara",'country_id' => 206),
		array('name' => "Monaragala",'country_id' => 206),
		array('name' => "Mullaitivu",'country_id' => 206),
		array('name' => "North Eastern Province",'country_id' => 206),
		array('name' => "North Western Province",'country_id' => 206),
		array('name' => "Nuwara Eliya",'country_id' => 206),
		array('name' => "Polonnaruwa",'country_id' => 206),
		array('name' => "Puttalama",'country_id' => 206),
		array('name' => "Ratnapuraya",'country_id' => 206),
		array('name' => "Southern Province",'country_id' => 206),
		array('name' => "Tirikunamalaya",'country_id' => 206),
		array('name' => "Tuscany",'country_id' => 206),
		array('name' => "Vavuniyawa",'country_id' => 206),
		array('name' => "Western Province",'country_id' => 206),
		array('name' => "Yapanaya",'country_id' => 206),
		array('name' => "kadawatha",'country_id' => 206),
		array('name' => "Abu Zabi",'country_id' => 229),
		array('name' => "Ajman",'country_id' => 229),
		array('name' => "Dubai",'country_id' => 229),
		array('name' => "Ras al-Khaymah",'country_id' => 229),
		array('name' => "Sharjah",'country_id' => 229),
		array('name' => "Sharjha",'country_id' => 229),
		array('name' => "Umm al Qaywayn",'country_id' => 229),
		array('name' => "al-Fujayrah",'country_id' => 229),
		array('name' => "ash-Shariqah",'country_id' => 229),
		array('name' => "Aberdeen",'country_id' => 230),
		array('name' => "Aberdeenshire",'country_id' => 230),
		array('name' => "Argyll",'country_id' => 230),
		array('name' => "Armagh",'country_id' => 230),
		array('name' => "Bedfordshire",'country_id' => 230),
		array('name' => "Belfast",'country_id' => 230),
		array('name' => "Berkshire",'country_id' => 230),
		array('name' => "Birmingham",'country_id' => 230),
		array('name' => "Brechin",'country_id' => 230),
		array('name' => "Bridgnorth",'country_id' => 230),
		array('name' => "Bristol",'country_id' => 230),
		array('name' => "Buckinghamshire",'country_id' => 230),
		array('name' => "Cambridge",'country_id' => 230),
		array('name' => "Cambridgeshire",'country_id' => 230),
		array('name' => "Channel Islands",'country_id' => 230),
		array('name' => "Cheshire",'country_id' => 230),
		array('name' => "Cleveland",'country_id' => 230),
		array('name' => "Co Fermanagh",'country_id' => 230),
		array('name' => "Conwy",'country_id' => 230),
		array('name' => "Cornwall",'country_id' => 230),
		array('name' => "Coventry",'country_id' => 230),
		array('name' => "Craven Arms",'country_id' => 230),
		array('name' => "Cumbria",'country_id' => 230),
		array('name' => "Denbighshire",'country_id' => 230),
		array('name' => "Derby",'country_id' => 230),
		array('name' => "Derbyshire",'country_id' => 230),
		array('name' => "Devon",'country_id' => 230),
		array('name' => "Dial Code Dungannon",'country_id' => 230),
		array('name' => "Didcot",'country_id' => 230),
		array('name' => "Dorset",'country_id' => 230),
		array('name' => "Dunbartonshire",'country_id' => 230),
		array('name' => "Durham",'country_id' => 230),
		array('name' => "East Dunbartonshire",'country_id' => 230),
		array('name' => "East Lothian",'country_id' => 230),
		array('name' => "East Midlands",'country_id' => 230),
		array('name' => "East Sussex",'country_id' => 230),
		array('name' => "East Yorkshire",'country_id' => 230),
		array('name' => "England",'country_id' => 230),
		array('name' => "Essex",'country_id' => 230),
		array('name' => "Fermanagh",'country_id' => 230),
		array('name' => "Fife",'country_id' => 230),
		array('name' => "Flintshire",'country_id' => 230),
		array('name' => "Fulham",'country_id' => 230),
		array('name' => "Gainsborough",'country_id' => 230),
		array('name' => "Glocestershire",'country_id' => 230),
		array('name' => "Gwent",'country_id' => 230),
		array('name' => "Hampshire",'country_id' => 230),
		array('name' => "Hants",'country_id' => 230),
		array('name' => "Herefordshire",'country_id' => 230),
		array('name' => "Hertfordshire",'country_id' => 230),
		array('name' => "Ireland",'country_id' => 230),
		array('name' => "Isle Of Man",'country_id' => 230),
		array('name' => "Isle of Wight",'country_id' => 230),
		array('name' => "Kenford",'country_id' => 230),
		array('name' => "Kent",'country_id' => 230),
		array('name' => "Kilmarnock",'country_id' => 230),
		array('name' => "Lanarkshire",'country_id' => 230),
		array('name' => "Lancashire",'country_id' => 230),
		array('name' => "Leicestershire",'country_id' => 230),
		array('name' => "Lincolnshire",'country_id' => 230),
		array('name' => "Llanymynech",'country_id' => 230),
		array('name' => "London",'country_id' => 230),
		array('name' => "Ludlow",'country_id' => 230),
		array('name' => "Manchester",'country_id' => 230),
		array('name' => "Mayfair",'country_id' => 230),
		array('name' => "Merseyside",'country_id' => 230),
		array('name' => "Mid Glamorgan",'country_id' => 230),
		array('name' => "Middlesex",'country_id' => 230),
		array('name' => "Mildenhall",'country_id' => 230),
		array('name' => "Monmouthshire",'country_id' => 230),
		array('name' => "Newton Stewart",'country_id' => 230),
		array('name' => "Norfolk",'country_id' => 230),
		array('name' => "North Humberside",'country_id' => 230),
		array('name' => "North Yorkshire",'country_id' => 230),
		array('name' => "Northamptonshire",'country_id' => 230),
		array('name' => "Northants",'country_id' => 230),
		array('name' => "Northern Ireland",'country_id' => 230),
		array('name' => "Northumberland",'country_id' => 230),
		array('name' => "Nottinghamshire",'country_id' => 230),
		array('name' => "Oxford",'country_id' => 230),
		array('name' => "Powys",'country_id' => 230),
		array('name' => "Roos-shire",'country_id' => 230),
		array('name' => "SUSSEX",'country_id' => 230),
		array('name' => "Sark",'country_id' => 230),
		array('name' => "Scotland",'country_id' => 230),
		array('name' => "Scottish Borders",'country_id' => 230),
		array('name' => "Shropshire",'country_id' => 230),
		array('name' => "Somerset",'country_id' => 230),
		array('name' => "South Glamorgan",'country_id' => 230),
		array('name' => "South Wales",'country_id' => 230),
		array('name' => "South Yorkshire",'country_id' => 230),
		array('name' => "Southwell",'country_id' => 230),
		array('name' => "Staffordshire",'country_id' => 230),
		array('name' => "Strabane",'country_id' => 230),
		array('name' => "Suffolk",'country_id' => 230),
		array('name' => "Surrey",'country_id' => 230),
		array('name' => "Sussex",'country_id' => 230),
		array('name' => "Twickenham",'country_id' => 230),
		array('name' => "Tyne and Wear",'country_id' => 230),
		array('name' => "Tyrone",'country_id' => 230),
		array('name' => "Utah",'country_id' => 230),
		array('name' => "Wales",'country_id' => 230),
		array('name' => "Warwickshire",'country_id' => 230),
		array('name' => "West Lothian",'country_id' => 230),
		array('name' => "West Midlands",'country_id' => 230),
		array('name' => "West Sussex",'country_id' => 230),
		array('name' => "West Yorkshire",'country_id' => 230),
		array('name' => "Whissendine",'country_id' => 230),
		array('name' => "Wiltshire",'country_id' => 230),
		array('name' => "Wokingham",'country_id' => 230),
		array('name' => "Worcestershire",'country_id' => 230),
		array('name' => "Wrexham",'country_id' => 230),
		array('name' => "Wurttemberg",'country_id' => 230),
		array('name' => "Yorkshire",'country_id' => 230),
		array('name' => "Alabama",'country_id' => 231),
		array('name' => "Alaska",'country_id' => 231),
		array('name' => "Arizona",'country_id' => 231),
		array('name' => "Arkansas",'country_id' => 231),
		array('name' => "Byram",'country_id' => 231),
		array('name' => "California",'country_id' => 231),
		array('name' => "Cokato",'country_id' => 231),
		array('name' => "Colorado",'country_id' => 231),
		array('name' => "Connecticut",'country_id' => 231),
		array('name' => "Delaware",'country_id' => 231),
		array('name' => "District of Columbia",'country_id' => 231),
		array('name' => "Florida",'country_id' => 231),
		array('name' => "Georgia",'country_id' => 231),
		array('name' => "Hawaii",'country_id' => 231),
		array('name' => "Idaho",'country_id' => 231),
		array('name' => "Illinois",'country_id' => 231),
		array('name' => "Indiana",'country_id' => 231),
		array('name' => "Iowa",'country_id' => 231),
		array('name' => "Kansas",'country_id' => 231),
		array('name' => "Kentucky",'country_id' => 231),
		array('name' => "Louisiana",'country_id' => 231),
		array('name' => "Lowa",'country_id' => 231),
		array('name' => "Maine",'country_id' => 231),
		array('name' => "Maryland",'country_id' => 231),
		array('name' => "Massachusetts",'country_id' => 231),
		array('name' => "Medfield",'country_id' => 231),
		array('name' => "Michigan",'country_id' => 231),
		array('name' => "Minnesota",'country_id' => 231),
		array('name' => "Mississippi",'country_id' => 231),
		array('name' => "Missouri",'country_id' => 231),
		array('name' => "Montana",'country_id' => 231),
		array('name' => "Nebraska",'country_id' => 231),
		array('name' => "Nevada",'country_id' => 231),
		array('name' => "New Hampshire",'country_id' => 231),
		array('name' => "New Jersey",'country_id' => 231),
		array('name' => "New Jersy",'country_id' => 231),
		array('name' => "New Mexico",'country_id' => 231),
		array('name' => "New York",'country_id' => 231),
		array('name' => "North Carolina",'country_id' => 231),
		array('name' => "North Dakota",'country_id' => 231),
		array('name' => "Ohio",'country_id' => 231),
		array('name' => "Oklahoma",'country_id' => 231),
		array('name' => "Ontario",'country_id' => 231),
		array('name' => "Oregon",'country_id' => 231),
		array('name' => "Pennsylvania",'country_id' => 231),
		array('name' => "Ramey",'country_id' => 231),
		array('name' => "Rhode Island",'country_id' => 231),
		array('name' => "South Carolina",'country_id' => 231),
		array('name' => "South Dakota",'country_id' => 231),
		array('name' => "Sublimity",'country_id' => 231),
		array('name' => "Tennessee",'country_id' => 231),
		array('name' => "Texas",'country_id' => 231),
		array('name' => "Trimble",'country_id' => 231),
		array('name' => "Utah",'country_id' => 231),
		array('name' => "Vermont",'country_id' => 231),
		array('name' => "Virginia",'country_id' => 231),
		array('name' => "Washington",'country_id' => 231),
		array('name' => "West Virginia",'country_id' => 231),
		array('name' => "Wisconsin",'country_id' => 231),
		array('name' => "Wyoming",'country_id' => 231)
		);
		DB::table('states')->insert($states);
	}
}
